apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Name}}
  namespace: {{$.Namespace}}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{$.Namespace}}
roleRef:
  kind: Role
  name: benchmark-role-0
  apiGroup: rbac.authorization.k8s.io
