apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Name}}
  labels:
    group: test-job
  annotations:
    kueue.x-k8s.io/queue-name: {{.LocalQueue}}  
spec:
  suspend: true
  parallelism: {{.Replicas}}
  completions: {{.Replicas}}
  completionMode: {{.Mode}}
  template:
    metadata:
      labels:
        group: test-pod
    spec:
      containers:
      - name: {{.Name}}
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
        args:
          - "30s"
        resources:
          requests:
            cpu: "300m"
            memory: "200Mi"          
      restartPolicy: Never
